Feature/lattices (#5)
* Tensor+LinAlg mat_exp

 - There is no in-place torch built-in, hence the ugly
        `data_ = f(data_)`
 - A simple test that shows that matexp(0) = 1 (as a matrix truth).

* Test of exponentiating a diagonal matrix.

 - Doesn't compile when the NSL::complex cases are included.
 - FAILS when the numbers are required to be too close.  This may be an
   actual concern, in terms of numerical stability / loss of precision.

* Fix rand() to populate Tensors correctly.

* Added NSL::LinAlg::abs, moved NSL::LinAlg::exp into own file

* Added system dependend limit calculations, inserted NSL::LinAlg functions rather then std where necessary

* Fix include ifndef/defines

 - Clean up accomplished TODO.

* (Failing) Test: exponential of hermitian matrix

* Remove explicit sizes from constructor.

* Added NSL::Tensor::real, NSL::Tensor::imag

* Added NSL::TimeTensor::real, NSL::TimeTensor::imag

* Test for exp(H) still fails.

 - Three methods for computing the determinant:
        - exp(tr H)
        - det[ U exp(H) U† ]
        - det[ exp(UHU†) ]
   but none seem to agree (or even come close).

 - A variety of outstanding TODOs to make it a bona-fide actual test.

* TYPO: missing tab.

* Use to_torch friend to get det, logdet in LinAlg

Previously, [log]det was a mutation on the internal data,
which required a fully copy in order to implement a non-member,
non-destructive [log]det.

Now, neither is a Tensor method, neither is destructive.  Both live
as stand-alone methods in LinAlg.

* Reorder steps in Hermitian test for legibility.

 - Put different determinant computations near one another.

* TYPO: fix banner alignment.

* First Pass: Lattice Base + Ring Implementation

 - Currently gets a linking error.
```
Undefined symbols for architecture x86_64:
  "NSL::Lattice::SpatialLatticeBase<double>::sites()", referenced from:
      void test_ring<double>(long const&) in test_ring.cpp.o
  "NSL::Lattice::SpatialLatticeBase<float>::sites()", referenced from:
      void test_ring<float>(long const&) in test_ring.cpp.o
  "NSL::Lattice::Ring<double>::Ring(unsigned int)", referenced from:
      void test_ring<double>(long const&) in test_ring.cpp.o
  "NSL::Lattice::Ring<float>::Ring(unsigned int)", referenced from:
      void test_ring<float>(long const&) in test_ring.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Tests/Lattice/CMakeFiles/test_ring.dir/build.make:119: Tests/Lattice/test_ring] Error 1
make[1]: *** [CMakeFiles/Makefile2:514: Tests/Lattice/CMakeFiles/test_ring.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
TODOs:
 - Ring takes real amplitude hopping only, should take complex.
 - Actually compute adjacency matrix from hopping.
 - Meaningful assertions about SpatialLatticeBase upon construction.
 - Get linear index, given a site.

* Added default constructor @ NSL::Tensor, NSL::TimeTensor, because std::map (required in coming commits) tries to default construct???

* included type_traits required by assertm

* Prepare NSL::Lattice::SpatialLatticeBase to be a parent

* NSL::Lattice::Ring is now correctly inherting from NSL::Lattice::SpatialLatticeBase, added CMakeLists to folder src/NSL/Lattice/Implementations

* Changed to size_type = std::size_t, commented REQUIRE(false)

* turned of warning narrowing

* Conditionally compute the adjacency matrix.

* Lattice and Lattice::Ring documentation

Additionally, move Lattice.adj_ to private, to ensure that everybody
else must use adjacency_matrix(), which is required to ensure that adj_
actually gets initialized (it's only computed on demand).

* Rename SpatialLatticeBase -> SpatialLattice

Aside from being shorter, it makes the code more (English-)idiomatic.
That is, you can read a piece of code and say
> Here I have a SpatialLattice

* Ring name gets parens.

* Sites have coordinates; Ring as an example.

* test_ring tries to print coordinates; SIGABRT.

* Use circular language for Rings.

* simplified Tensor::operator=, added Tensor::conj

* added test for Tensor::operator=

* Changed Lattice::Site -> Tensor, added Lattice::SpatialLattice::coordinates

* Added doxygen strings test_ring.cpp & ring.cpp

* Lattice::coordinates docstring

* Fix type of hypothetical site lookup operator.

* SpatialLattice::adjacency_matrix: <int> or <bool>?

* Additional unimplemented test_ring tests

* test_ring doxygen boilerplate.

* test_ring: enable different hopping amplitudes

* Additional ideas for test_ring

Co-authored-by: Marcel Rodekamp <marcel.rodekamp@gmail.com>
Co-authored-by: Marcel Rodekamp <32614876+Marcel-Rodekamp@users.noreply.github.com>