Feature/file io (#126)
* first round of commits for testing h5 input/output

* preparing h5_io template

* Nt and Nx are now written as an attribute for each dataset

* started working on h5 class

* more on h5 io stuff

* highfive.cmake

* minor edits

* more work by yours truly

* fixed some errors

* addd truncate option

* starting inner workings of a read function

* fixed an typecast issue

* ok, starting to write a rudimentary read function.  can now load attributes

* Added Tensor::reshape

* can now read data from h5 file into an std::vector

* ok, with help from Marcel, can now read and write a tensor of arbitrary dim to h5.  still need to write some logic to check things

* cleaned up example_IO.cpp

* more logic

* Added Tensor::resize

* ok, read/write of arbitrary tensor to h5 now works.  on to configurations next!

* overloaded constructor so that it can take filehandling as argument

* overloaded write function to take NSL::Configuration as an argument.  it compiles surprisingly. . .

* ok, the overloaded read function also compiles!  I am very suspicious. . .

* configurations can be written and read

* thanks to Marcel we fixed a bug with reading configurations

* check if node has '/' at the end or not, and act accordingly

* acceptence --> acceptance

* Marcel is a slave driver

* more acceptence --> acceptance

* first pass at read/write of a markov state

* testing read/write markovstate

* can now write out a complex markovstate

* markov state reader can now find the most recent state

* can read in markov state.  function overloads such that one can read in a specific state, or else the routine finds the most recent state and loads it in

* removed unnecessary string definition

* incorporated Giovanni's logger

* h5io now writes out the tensor type as an attribute, and checks that type is consistent when reading tensors

* Fixed compilation error: consexpr char+string in logging calls

* removed use of namespace HighFive.  all HighFive routines are now explicitly called with HighFive:: prepended.  Also put the HighFive::File handling under the NSL namespace.  ARE YOU HAPPY NOW, MARCEL (THE SLAVE DRIVER)?

---------

Co-authored-by: Thomas Luu <t.luu@fz-juelich.de>
Co-authored-by: Marcel Rodekamp <marcel.rodekamp@gmail.com>